# Dataset Parameters
num_classes: 5
labels_to_class: {0:'daisy',1:'dandelion',2:'rose',3:'sunflower',4:'tulip'}
class_to_labels: {'daisy':0,'dandelion':1,'rose':2,'sunflower':3,'tulip':4}

#paths
root_path: 'D:\2020\Trainings\self-supervised-learning'
data_path: 'dataset'
save_dir: 'sl_exp_1'
imgs_dir: 'flowers'
labels_dir: 'annotations'

# Self Supervised Params
pretext: 'rotation'
num_rot: 4

#model parameters
network: 'resnet18'
lr: 1e-2
momentum: 9e-1

# Training Parameters
num_epochs: 1
batch_size: 10
mean_norm: False
mean_val: [0,0,0]
std_val: [255,255,255]
img_sz: 100
cuda_num: 2
use_cuda: False

#saving parameters
save_intermediate_weights: 10 # After how many epoch to save the weights



