# Dataset Parameters
num_classes: 5
# define lebels to class dictionary
labels_to_class:
  0: 'daisy'
  1: 'dandelion'
  2: 'rose'
  3: 'sunflower'
  4: 'tulip'

mean_val: [0.57711623,0.57658564,0.47776383]#[147.16463878,147.02933698,121.82977662]
std_val: [0.09158824,0.09528065,0.20864842]#[23.35500145,24.29656621,53.20534792]

#class_to_labels: {'daisy':0,'dandelion':1,'rose':2,'sunflower':3,'tulip':4}

#paths
root_path: 'D:\2020\Trainings\self_supervised_learning'
data_path: 'dataset'
exp_type: 'supervised' # 'supervised' or 'self-supervised'
save_dir: 'sl_exp_3'
imgs_dir: 'flowers'
labels_dir: 'annotations'
log: 'train.log'

# Self Supervised Params
pretext: False
num_rot: 4

#supervised params
use_pretrained: False
ssl_pretrained_exp_path: 'ssl_exp_1'
ssl_weight: 'resnet18_4rot_epoch0_best.pth'

#model parameters
network: 'resnet18'
lr: 1e-2
momentum: 9e-1
scheduler: False
opt: 'sgd'

# Training Parameters
num_epochs: 5
batch_size: 2
mean_norm: False
img_sz: 100
val_split: 0.2
cuda_num: 2
use_cuda: False
data_aug: False #['randomhorizontalflip','randomcrop']# None

# pretrained model


#saving parameters
save_intermediate_weights: 2 # After how many epoch to save the weights



